name: 玩家举报
title: "[玩家举报]"
description: 有玩家出现了违规行为
assignees: IlyaYezelovsky
body:
  - type: input
    id: input-0
    attributes:
      label: 被举报玩家名
      description: 存在违规行为的玩家ID或昵称等信息，可输入多个
    validations:
      required: true
  - type: dropdown
    id: dropdown-1
    attributes:
      label: 举报类型
      multiple: true
      description: 违规行为的类型，可选择多个
      options:
        - 影响服务器正常运行
        - 使其他玩家无法正常连接
        - 聊天不适当内容
        - 现实货币交易
    validations:
      required: true
  - type: textarea
    id: textarea-2
    attributes:
      label: 描述
      description: 可提交举报证据
    validations:
      required: true
